#libevent 三方库引
include(ExternalProject)

set(LIBEVENT_ROOT ${CMAKE_BINARY_DIR}/third_party/libevent)

set(LIBEVENT_SOURCE_DIR ${CMAKE_SOURCE_DIR}/third_party/libevent)

set(LIBEVENT_CONFIGURE cd ${LIBEVENT_ROOT} && cmake ${LIBEVENT_SOURCE_DIR}
-DCMAKE_BUILD_TYPE=Debug
-DEVENT_INSTALL_BIN_DIR=${LIBEVENT_ROOT}/install/bin
-DEVENT_INSTALL_CMAKE_DIR=${LIBEVENT_ROOT}/install/lib/cmake/libevent
-DEVENT_INSTALL_INCLUDE_DIR=${LIBEVENT_ROOT}/install/include
-DEVENT_INSTALL_LIB_DIR=${LIBEVENT_ROOT}/install/lib)

set(LIBEVENT_MAKE cd ${LIBEVENT_ROOT} && make)
set(LIBEVENT_INSTALL cd ${LIBEVENT_ROOT} && make install)

ExternalProject_Add(LIBEVENT
	PREFIX ${LIBEVENT_ROOT}
	CONFIGURE_COMMAND ${LIBEVENT_CONFIGURE}
	BUILD_COMMAND ${LIBEVENT_MAKE}
	INSTALL_COMMAND ${LIBEVENT_INSTALL}
	SOURCE_DIR ${LIBEVENT_SOURCE_DIR})

set(LIBEVENT_LIB ${LIBEVENT_ROOT}/lib/libevent_core.a)

set(LIBEVENT_INCLUDE_DIR ${LIBEVENT_ROOT}/include)
